# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 951, 651))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_mainWindow = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_mainWindow.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_mainWindow.setObjectName("horizontalLayout_mainWindow")
        self.verticalLayout_videoSection = QtWidgets.QVBoxLayout()
        self.verticalLayout_videoSection.setObjectName("verticalLayout_videoSection")
        self.label_videoPlaceHolder = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_videoPlaceHolder.setObjectName("label_videoPlaceHolder")
        self.verticalLayout_videoSection.addWidget(self.label_videoPlaceHolder)
        self.horizontalLayout_buttonSection = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttonSection.setObjectName("horizontalLayout_buttonSection")
        self.pushButton_start = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_buttonSection.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_buttonSection.addWidget(self.pushButton_stop)
        self.verticalLayout_videoSection.addLayout(self.horizontalLayout_buttonSection)
        self.verticalLayout_videoSection.setStretch(0, 8)
        self.verticalLayout_videoSection.setStretch(1, 2)
        self.horizontalLayout_mainWindow.addLayout(self.verticalLayout_videoSection)
        self.verticalLayout_riskEventSection = QtWidgets.QVBoxLayout()
        self.verticalLayout_riskEventSection.setObjectName("verticalLayout_riskEventSection")
        self.label_RiskEvent = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_RiskEvent.setObjectName("label_RiskEvent")
        self.verticalLayout_riskEventSection.addWidget(self.label_RiskEvent)
        self.listWidget_risikEvent = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.listWidget_risikEvent.setObjectName("listWidget_risikEvent")
        self.verticalLayout_riskEventSection.addWidget(self.listWidget_risikEvent)
        self.horizontalLayout_mainWindow.addLayout(self.verticalLayout_riskEventSection)
        self.horizontalLayout_mainWindow.setStretch(0, 7)
        self.horizontalLayout_mainWindow.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_videoPlaceHolder.setText(_translate("MainWindow", "Video"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.label_RiskEvent.setText(_translate("MainWindow", "Risk Event"))
